/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainframe;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author Hello there!
 */
public class DateEditor extends javax.swing.JFrame
{

    private static ArrayList<Double> loadedData;
    private static HashMap<Profile, ArrayList<Double>> data;

    /**
     * Creates new form InputTimeData
     */
    public DateEditor()
    {
        loadedData = DataManager.getDateData(DateSelection.date.toString()).get(ProfileSelection.selectedProfile);
        
        if (loadedData == null)
        {
            loadedData = new ArrayList<>();
            for (int i = 0; i < 5; i++)
            {
                loadedData.add(-1.0);
            }
        }

        data = DataManager.getDateData(DateSelection.date.toString());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") // This messy code bothers me, but I can't change it.
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButtonBack = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jFormattedTextFieldFreestyle100 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldBackstroke50 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldBackstroke100 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldBreaststroke50 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldButterfly50 = new javax.swing.JFormattedTextField();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBack.setText("<-- Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBackActionPerformed(evt);
            }
        });
        setResizable(false);
        setTitle("Enter Swim Times");

        jButtonUpdate.setText("Update Table");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabel1.setText("Freestyle 100");

        jLabel2.setText(mainframe.ProfileSelection.selectedProfile.getAge() <= 12 ? "Backstroke 50" : "Backstroke 200");

        jLabel3.setText("Backstroke 100");

        jLabel4.setText(mainframe.ProfileSelection.selectedProfile.getAge() <= 12 ? "Breaststroke 50" : "Breaststroke 100");

        jLabel5.setText(mainframe.ProfileSelection.selectedProfile.getAge() <= 12 ? "Butterfly 50" : "Butterfly 100");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        addTextToField(jFormattedTextFieldFreestyle100, loadedData.get(0));
        jFormattedTextFieldFreestyle100.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                decimalOnly(evt);
            }
        });

        addTextToField(jFormattedTextFieldBackstroke50, loadedData.get(1));
        jFormattedTextFieldBackstroke50.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                decimalOnly(evt);
            }
        });

        addTextToField(jFormattedTextFieldBackstroke100, loadedData.get(2));
        jFormattedTextFieldBackstroke100.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                decimalOnly(evt);
            }
        });

        addTextToField(jFormattedTextFieldBreaststroke50, loadedData.get(3));
        jFormattedTextFieldBreaststroke50.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                decimalOnly(evt);
            }
        });

        addTextToField(jFormattedTextFieldButterfly50, loadedData.get(4));
        jFormattedTextFieldButterfly50.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                decimalOnly(evt);
            }
        });

        jButtonDelete.setText("Delete Data");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jFormattedTextFieldFreestyle100, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jFormattedTextFieldBackstroke50, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jFormattedTextFieldBackstroke100, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jFormattedTextFieldBreaststroke50, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jFormattedTextFieldButterfly50, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldBackstroke100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jFormattedTextFieldBackstroke50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFormattedTextFieldFreestyle100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jFormattedTextFieldBreaststroke50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldButterfly50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete))
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBackActionPerformed
    {//GEN-HEADEREND:event_jButtonBackActionPerformed
        java.awt.EventQueue.invokeLater(() -> new DateSelection().setVisible(true));
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonUpdateActionPerformed
    {//GEN-HEADEREND:event_jButtonUpdateActionPerformed

        ArrayList<Double> newData = new ArrayList<>();

        newData.add(parseDouble(jFormattedTextFieldFreestyle100.getText()));
        newData.add(parseDouble(jFormattedTextFieldBackstroke50.getText()));
        newData.add(parseDouble(jFormattedTextFieldBackstroke100.getText()));
        newData.add(parseDouble(jFormattedTextFieldBreaststroke50.getText()));
        newData.add(parseDouble(jFormattedTextFieldButterfly50.getText()));

        data.put(ProfileSelection.selectedProfile, newData);
        DataManager.storeDateData(DateSelection.date, data);

        System.out.println(data);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * Converts string to double, but returns -1 if string is empty.
     *
     * @param s
     * @return
     */
    public static double parseDouble(String s)
    {
        try
        {
            return Double.parseDouble(s);
        } catch (NumberFormatException ex)
        {
            return -1;
        }
    }

    /**
     * Adds numbers to JFormattedTextField, or leaves it empty if number = -1.
     * 
     * @param field
     * @param d 
     */
    private static void addTextToField(JFormattedTextField field, double d)
    {
        if (d == -1)
        {
            field.setText("");
            return;
        }
        field.setText(d + "");
    }

    /**
     * Ensure that only real numbers are entered into field.
     *
     * @param evt
     */
    private void decimalOnly(java.awt.event.KeyEvent evt)//GEN-FIRST:event_decimalOnly
    {//GEN-HEADEREND:event_decimalOnly
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) && c != '.')
        {
            evt.consume();
        }

        JFormattedTextField j = (JFormattedTextField) evt.getComponent();
        if (c == '.' && (j.getText().length() < 1 || charFreq('.', j.getText()) > 0))
        {
            evt.consume();
        }

    }//GEN-LAST:event_decimalOnly

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDeleteActionPerformed
    {//GEN-HEADEREND:event_jButtonDeleteActionPerformed
        if (ProfileSelection.showQuestionDialog("Delete data?"))
        {
            data.remove(ProfileSelection.selectedProfile);
            DataManager.storeDateData(DateSelection.date, data);
            java.awt.EventQueue.invokeLater(() -> new DateSelection().setVisible(true));
            this.dispose();
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * Get number of times a character appears in string.
     *
     * @param c
     * @param s
     * @return
     */
    public static int charFreq(char c, String s)
    {
        char[] arr = s.toCharArray();
        int n = 0;
        for (char i : arr)
        {
            if (i == c)
            {
                n++;
            }
        }
        return n;
    }

    /**
     * @param args the command line arguments
     */

    //<editor-fold defaultstate="collapsed" desc="Disabled code">

    /*public void addObjectToTable(JTable table, ArrayList<Object> items)
     {
     for (int i = 0; i < items.size(); i++)
     {
     try
     {
     TableColumn column = table.getColumnModel().getColumn(i);
     column.setCellEditor(new DefaultCellEditor((JFormattedTextField) items.get(i)));
     } catch (ArrayIndexOutOfBoundsException ex)
     {
     return;
     } catch (NullPointerException ex)
     {
     System.out.println((JFormattedTextField) items.get(i));
     }
     }
     }*/
     //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JFormattedTextField jFormattedTextFieldBackstroke100;
    private javax.swing.JFormattedTextField jFormattedTextFieldBackstroke50;
    private javax.swing.JFormattedTextField jFormattedTextFieldBreaststroke50;
    private javax.swing.JFormattedTextField jFormattedTextFieldButterfly50;
    private javax.swing.JFormattedTextField jFormattedTextFieldFreestyle100;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
