/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainframe;

import java.io.FileNotFoundException;
import java.util.*;

/**
 *
 * @author Hello there!
 */
public class NationalStandards extends javax.swing.JFrame
{

    private ArrayList<Double> _nationalStats;
    private double[] nationalStats;
    
    /**
     * Creates new form NationalStats
     * @throws java.io.FileNotFoundException
     */
    public NationalStandards() throws FileNotFoundException
    {
        // load the data from memory, then convert it into an array
        _nationalStats = DataManager.getNationalStandards(ProfileSelection.selectedProfile.getGender(), ProfileSelection.selectedProfile.getAge());
        nationalStats = new double[_nationalStats.size()];
        for (int i = 0; i < nationalStats.length; i++)
        {
            nationalStats[i] = _nationalStats.get(i);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButtonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBack.setText("<-- Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBackActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Overview", Stat.mean(StatsViewer.allData) - Stat.mean(nationalStats)},
                {"Freestyle 100", Stat.mean(StatsViewer.freestyle100) - nationalStats[0]},
                {mainframe.ProfileSelection.selectedProfile.getAge() <= 12 ? "Backstroke 50" : "Backstroke 200", Stat.mean(StatsViewer.backstroke50) - nationalStats[1]},
                {"Backstroke 100", Stat.mean(StatsViewer.backstroke100) - nationalStats[2]},
                {mainframe.ProfileSelection.selectedProfile.getAge() <= 12 ? "Breaststroke 50" : "Breaststroke 100", Stat.mean(StatsViewer.breaststroke50) - nationalStats[3]},
                {mainframe.ProfileSelection.selectedProfile.getAge() <= 12 ? "Butterfly 50" : "Butterfly 100", Stat.mean(StatsViewer.butterfly50) - nationalStats[4]}
            },
            new String []
            {
                "Title 1", "Title 2"
            }
        ));
        setResizable(false);
        setTitle("Compare Against National Standards");
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("<html>This table compares your swim times against<br>the national standards for your gender and age.<br>A positive value indicates that your<br>time is greater than the standard,<br>while a negative value indicates that your time is below it.</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBack)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBackActionPerformed
    {//GEN-HEADEREND:event_jButtonBackActionPerformed
        java.awt.EventQueue.invokeLater(() -> new StatsViewer().setVisible(true));
        this.dispose();      
        
    }//GEN-LAST:event_jButtonBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
