/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainframe;

import java.text.NumberFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.text.NumberFormatter;
import static mainframe.DataManager.*;

/**
 *
 * @author Hello there!
 */
public class ProfileSelection extends javax.swing.JFrame
{

    private static String name;
    private static int age;
    private static Gender gender;
    public static ArrayList<Profile> profiles;
    public static int currentId;
    public static Profile selectedProfile;

    private static boolean addProfileMode = true;
    private static Profile activeProfile;

    /**
     * Creates new form MainFrame
     */
    public ProfileSelection()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonAddProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox();
        jTextFieldName = new javax.swing.JTextField();
        NumberFormat format = NumberFormat.getInstance();
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum (Integer.MAX_VALUE);
        formatter.setAllowsInvalid (false);
        formatter.setCommitsOnValidEdit (true);
        jFormattedTextFieldAge = new javax.swing.JFormattedTextField(formatter);
        jButtonCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxProfiles = new javax.swing.JComboBox();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSelect = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jFormattedTextField2.setText("jFormattedTextField2");

        jScrollPane1.setViewportView(jEditorPane1);

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAddProfile.setText("Add Profile");
        jButtonAddProfile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddProfileActionPerformed(evt);
            }
        });

        jLabel1.setText("Name: ");

        jLabel3.setText("Age:");

        jLabel4.setText("Gender:");

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Male", "Female"}));

        //JOptionPane.showMessageDialog(null, jFormattedTextFieldAge);

        jButtonCancel.setText("Cancel Edit");
        jButtonCancel.setVisible(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddProfile))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel7.setText("Select Profile: ");

        jComboBoxProfiles.setModel(new javax.swing.DefaultComboBoxModel(Profile.getNames(profiles)));
        setResizable(false);
        setTitle("Profile selection");

        jButtonEdit.setText("Edit Profile");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete Profile");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSelect.setText("Next Page -->");
        jButtonSelect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSelectActionPerformed(evt);
            }
        });

        jLabel6.setText("Add new profile or edit selected profile:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(29, 29, 29)
                            .addComponent(jComboBoxProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonDelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButtonEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonSelect)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProfileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddProfileActionPerformed
    {//GEN-HEADEREND:event_jButtonAddProfileActionPerformed
        if (Arrays.asList(Profile.getNames(profiles)).contains(jTextFieldName.getText()) && addProfileMode) // prevent multiple profiles using same name
        {
            // display error message if name already taken
            showWarningDialog("Name already taken.");
        } else if (jTextFieldName.getText().length() > 0 && jFormattedTextFieldAge.getText().length() > 0) // only proceed if all fields are filled
        {
            name = jTextFieldName.getText();
            age = Integer.parseInt(jFormattedTextFieldAge.getText().replaceAll(",", ""));
            gender = jComboBoxGender.getSelectedIndex() == 0 ? Gender.MALE : Gender.FEMALE;
            if (addProfileMode)
            {
                profiles.add(new Profile(name, age, gender));
            } else
            {
                String temp = activeProfile.getName();
                activeProfile.setName(name);
                if (Collections.frequency(new ArrayList<>(Arrays.asList(Profile.getNames(profiles))), name) > 1) // make sure that when editing profile, it doesn't take name of other profile apart from its own
                {
                    showWarningDialog("Name already taken.");
                    activeProfile.setName(temp); // set the profile back to its original name
                    return;
                }
                activeProfile.setAge(age);
                activeProfile.setGender(gender);
                jButtonAddProfile.setText("Add Profile");
                addProfileMode = true;
            }
            storeProfileData(profiles);
            jButtonCancel.setVisible(false);
            clearFields();
            jComboBoxProfiles.setModel(new javax.swing.DefaultComboBoxModel(Profile.getNames(profiles)));
        } else
        {
            showWarningDialog("Please complete the form.");
        }
    }//GEN-LAST:event_jButtonAddProfileActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDeleteActionPerformed
    {//GEN-HEADEREND:event_jButtonDeleteActionPerformed

        if (showQuestionDialog("Delete Profile?"))
        {
            for (Profile p : profiles)
            {
                if (p.getName().equals(jComboBoxProfiles.getSelectedItem().toString()))
                {
                    profiles.remove(p);
                    jComboBoxProfiles.setModel(new javax.swing.DefaultComboBoxModel(Profile.getNames(profiles)));
                    break;
                }
            }
            addProfileMode = true;
            storeProfileData(profiles);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEditActionPerformed
    {//GEN-HEADEREND:event_jButtonEditActionPerformed
        if (jComboBoxProfiles.getSelectedItem() != null)
        {
            addProfileMode = false;
            activeProfile = Profile.getProfileWithName(profiles, jComboBoxProfiles.getSelectedItem().toString());
            jTextFieldName.setText(activeProfile.getName());
            jFormattedTextFieldAge.setText(Integer.toString(activeProfile.getAge()));
            jComboBoxGender.setSelectedIndex(activeProfile.getGender() == Gender.MALE ? 0 : 1);
            jButtonAddProfile.setText("Edit Profile");
            jButtonCancel.setVisible(true);
        } else
        {
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSelectActionPerformed
    {//GEN-HEADEREND:event_jButtonSelectActionPerformed
        selectedProfile = Profile.getProfileWithName(profiles, jComboBoxProfiles.getSelectedItem().toString());
        java.awt.EventQueue.invokeLater(() -> new DateSelection().setVisible(true));
        this.dispose();
    }//GEN-LAST:event_jButtonSelectActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        addProfileMode = true;
        jButtonCancel.setVisible(false);
        jButtonAddProfile.setText("Add Profile");
        clearFields();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * Displays warning dialog.
     *
     * @param msg The text in the dialog.
     */
    public static void showWarningDialog(String msg)
    {
        final JOptionPane warning = new JOptionPane(msg, JOptionPane.ERROR_MESSAGE, JOptionPane.DEFAULT_OPTION);
        JOptionPane.showMessageDialog(warning, msg);
    }

    /**
     * Shows yes/no question dialog
     *
     * @param msg The text in the dialog.
     * @return true if the user clicked 'yes'.
     */
    public static boolean showQuestionDialog(String msg)
    {
        final JOptionPane optionPane = new JOptionPane(msg, JOptionPane.QUESTION_MESSAGE, JOptionPane.YES_NO_OPTION);
        int n = JOptionPane.showConfirmDialog(optionPane, msg, msg, JOptionPane.YES_NO_OPTION);
        return n == 0;
    }

    /**
     * Clears all fields in the add profile form
     */
    private void clearFields()
    {
        jFormattedTextFieldAge.setValue(null);
        jTextFieldName.setText("");
    }

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ProfileSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        profiles = getProfileData();
        java.awt.EventQueue.invokeLater(() -> new ProfileSelection().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddProfile;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JComboBox jComboBoxGender;
    private javax.swing.JComboBox jComboBoxProfiles;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextFieldAge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
